- hosts: webservers
  remote_user: ec2-user
  become: yes
  tasks:
    - name: downloading tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.tar.gz
        dest: /opt
    - name: extracting tomcat
      unarchive:
        src: /opt/apache-tomcat-10.1.6.tar.gz
        dest: /opt
        remote_src: yes
    - name: installing java
      yum:
       name: java-11-amazon-corretto
       state: present
    - name: downloading tomcat
      get_url:
        url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
        dest: /opt/apache-tomcat-10.1.6/webapps
    - name: starting tomcat
      shell: nohup /opt/apache-tomcat-10.1.6/bin/shutdown.sh &
    - name: starting tomcat
      shell: nohup /opt/apache-tomcat-10.1.6/bin/startup.sh &
